plugins {
    id "java-conventions"
    id "com.gradle.plugin-publish"
    id "com.gradleup.shadow"
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

tasks.named("shadowJar") {
    archiveClassifier = ""
    configurations = project.configurations.named("bundled").map { [it] }
    actions.removeAt(0) // remove manifest Class-Path configuration action that requires platform in configuration
}

configurations {
    bundled.extendsFrom internalPlatform
}

dependencies {
    bundled project(":jdoc-gradle-plugin-commons")
    implementation project(":jdoc-gradle-plugin-commons")
}

afterEvaluate {
    configurations.runtimeClasspath.allDependencies.each { dep ->
        if (!configurations.bundled.allDependencies.any {
            it.group == dep.group && it.name == dep.name
        }) {
            dependencies.add("shadow", dep)
        }
    }
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}