name: Code Check
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.11.0
    - name: Run Gradle checks
      run: ./gradlew check
    - name: Upload failed test reports
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4.0.0
      with:
        name: reports
        path: '**/build/reports/**/*'
