name: release-please

on:
  workflow_run:
    workflows:
      - Code Check
    types:
      - completed
    branches:
      - master
      - release/[0-9]+.[0-9]+.x

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.1.2
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: java
          include-v-in-tag: false
